version: '3.8'

services:
  db:
    image: mongo:6-jammy
    container_name: mongodb-conduit
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - conduit-net
    healthcheck:
      test: ['CMD-SHELL', "mongosh --eval 'db.runCommand({ping:1})' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    image: conduit-app:v1
    container_name: conduit-api
    restart: always
    ports:
      - '${APP_PORT}:3000'
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGO_URI}
      - SECRET=${APP_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - conduit-net

networks:
  conduit-net:
    driver: bridge

volumes:
  mongo-data:
